export const FETCH_PROJECTS_REQUESTED = 'FETCH_PROJECTS_REQUESTED'
export const FETCH_PROJECTS_SUCCEEDED = 'FETCH_PROJECTS_SUCCEEDED'
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED'

export const FETCH_INTENTS_REQUESTED = 'FETCH_INTENTS_REQUESTED'
export const FETCH_INTENTS_SUCCEEDED = 'FETCH_INTENTS_SUCCEEDED'
export const FETCH_INTENTS_FAILED = 'FETCH_INTENTS_FAILED'

export const FETCH_CATEGORIES_REQUESTED = 'FETCH_CATEGORIES_REQUESTED'
export const FETCH_CATEGORIES_SUCCEEDED = 'FETCH_CATEGORIES_SUCCEEDED'
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED'

export const FETCH_LABELS_REQUESTED = 'FETCH_LABELS_REQUESTED'
export const FETCH_LABELS_SUCCEEDED = 'FETCH_LABELS_SUCCEEDED'
export const FETCH_LABELS_FAILED = 'FETCH_LABELS_FAILED'

export const FETCH_REVIEWS_REQUESTED = 'FETCH_REVIEWS_REQUESTED'
export const FETCH_REVIEWS_SUCCEEDED = 'FETCH_REVIEWS_SUCCEEDED'
export const FETCH_REVIEWS_FAILED = 'FETCH_REVIEWS_FAILED'

export const FETCH_PLACES_REQUESTED = 'FETCH_PLACES_REQUESTED'
export const FETCH_PLACES_SUCCEEDED = 'FETCH_PLACES_SUCCEEDED'
export const FETCH_PLACES_FAILED = 'FETCH_PLACES_FAILED'

export const FETCH_PERSON_REQUESTED = 'FETCH_PERSON_REQUESTED'
export const FETCH_PERSON_SUCCEEDED = 'FETCH_PERSON_SUCCEEDED'
export const FETCH_PERSON_FAILED = 'FETCH_PERSON_FAILED'

export const FETCH_PEOPLE_REQUESTED = 'FETCH_PEOPLE_REQUESTED'
export const FETCH_PEOPLE_SUCCEEDED = 'FETCH_PEOPLE_SUCCEEDED'
export const FETCH_PEOPLE_FAILED = 'FETCH_PEOPLE_FAILED'

export const FETCH_MY_CONVERSATIONS_REQUESTED = 'FETCH_MY_CONVERSATIONS_REQUESTED'
export const FETCH_MY_CONVERSATIONS_SUCCEEDED = 'FETCH_MY_CONVERSATIONS_SUCCEEDED'
export const FETCH_MY_CONVERSATIONS_FAILED = 'FETCH_MY_CONVERSATIONS_FAILED'

export const FETCH_NOTIFICATIONS_REQUESTED = 'FETCH_NOTIFICATIONS_REQUESTED'
export const FETCH_NOTIFICATIONS_SUCCEEDED = 'FETCH_NOTIFICATIONS_SUCCEEDED'
export const FETCH_NOTIFICATIONS_FAILED = 'FETCH_NOTIFICATIONS_FAILED'

export const ADD_MESSAGE_REQUESTED = 'ADD_MESSAGE_REQUESTED'
export const ADD_MESSAGE_SUCCEEDED = 'ADD_MESSAGE_SUCCEEDED'
export const ADD_MESSAGE_FAILED = 'ADD_MESSAGE_FAILED'

export const ADD_REVIEW_REQUESTED = 'ADD_REVIEW_REQUESTED'
export const ADD_REVIEW_SUCCEEDED = 'ADD_REVIEW_SUCCEEDED'
export const ADD_REVIEW_FAILED = 'ADD_REVIEW_FAILED'

export const SAVE_PLACE_REQUESTED = 'SAVE_PLACE_REQUESTED'
export const SAVE_PLACE_SUCCEEDED = 'SAVE_PLACE_SUCCEEDED'
export const SAVE_PLACE_FAILED = 'SAVE_PLACE_FAILED'

export const SAVE_SUBSCRIPTION_REQUESTED = 'SAVE_SUBSCRIPTION_REQUESTED'
export const SAVE_SUBSCRIPTION_SUCCEEDED = 'SAVE_SUBSCRIPTION_SUCCEEDED'
export const SAVE_SUBSCRIPTION_FAILED = 'SAVE_SUBSCRIPTION_FAILED'

export const SAVE_NOTIFICATION_REQUESTED = 'SAVE_NOTIFICATION_REQUESTED'
export const SAVE_NOTIFICATION_SUCCEEDED = 'SAVE_NOTIFICATION_SUCCEEDED'
export const SAVE_NOTIFICATION_FAILED = 'SAVE_NOTIFICATION_FAILED'

export const HELLO_REQUESTED = 'HELLO_REQUESTED'
export const HELLO_SUCCEEDED = 'HELLO_SUCCEEDED'
export const HELLO_FAILED = 'HELLO_FAILED'
export const BYE_REQUESTED = 'BYE_REQUESTED'
export const BYE_SUCCEEDED = 'BYE_SUCCEEDED'
export const BYE_FAILED = 'BYE_FAILED'

export const FOLLOW_REQUESTED = 'FOLLOW_REQUESTED'
export const FOLLOW_SUCCEEDED = 'FOLLOW_SUCCEEDED'
export const FOLLOW_FAILED = 'FOLLOW_FAILED'
export const UNFOLLOW_REQUESTED = 'UNFOLLOW_REQUESTED'
export const UNFOLLOW_SUCCEEDED = 'UNFOLLOW_SUCCEEDED'
export const UNFOLLOW_FAILED = 'UNFOLLOW_FAILED'

export const FAVOR_REQUESTED = 'FAVOR_REQUESTED'
export const FAVOR_SUCCEEDED = 'FAVOR_SUCCEEDED'
export const FAVOR_FAILED = 'FAVOR_FAILED'
export const UNFAVOR_REQUESTED = 'UNFAVOR_REQUESTED'
export const UNFAVOR_SUCCEEDED = 'UNFAVOR_SUCCEEDED'
export const UNFAVOR_FAILED = 'UNFAVOR_FAILED'

export const SAVE_INTENT_REQUESTED = 'SAVE_INTENT_REQUESTED'
export const SAVE_INTENT_SUCCEEDED = 'SAVE_INTENT_SUCCEEDED'
export const SAVE_INTENT_FAILED = 'SAVE_INTENT_FAILED'

export const SAVE_PROJECT_REQUESTED = 'SAVE_PROJECT_REQUESTED'
export const SAVE_PROJECT_SUCCEEDED = 'SAVE_PROJECT_SUCCEEDED'
export const SAVE_PROJECT_FAILED = 'SAVE_PROJECT_FAILED'

export const SAVE_PERSON_REQUESTED = 'SAVE_PERSON_REQUESTED'
export const SAVE_PERSON_SUCCEEDED = 'SAVE_PERSON_SUCCEEDED'
export const SAVE_PERSON_FAILED = 'SAVE_PERSON_FAILED'

export const START_CONVERSATION_REQUESTED = 'START_CONVERSATION_REQUESTED'
export const START_CONVERSATION_SUCCEEDED = 'START_CONVERSATION_SUCCEEDED'
export const START_CONVERSATION_FAILED = 'START_CONVERSATION_FAILED'
